import {
  Content,
  DescriptionList,
  DescriptionListDescription,
  DescriptionListGroup,
  DescriptionListTerm,
  Flex,
  FlexItem,
  Modal,
  ModalBody,
  ModalFooter,
  ModalHeader,
  Button,
} from "@patternfly/react-core";

import type { SigningKey } from "../../../api/client/pulpitCore/types";
import { StatusIndicator } from "../../../components/StatusIndicator";
import { formatRelativeTime } from "../../../lib/relativeTime";
import { SIGNING_KEY_STATE_COLOR, SIGNING_KEY_STATE_LABEL } from "./signingKeyState";
import { KeyPulpServicesStatus } from "./KeyPulpServicesStatus";
import { CopyableValue } from "./CopyableValue";

function DateValue({ value }: { value: string | null }) {
  return value ? <span title={value}>{formatRelativeTime(value)}</span> : <>—</>;
}

export function SigningKeyDetailsModal({
  signingKey,
  onClose,
}: {
  signingKey: SigningKey;
  onClose: () => void;
}) {
  return (
    <Modal
      isOpen
      onClose={onClose}
      aria-labelledby="signing-key-details-title"
      variant="medium"
    >
      <ModalHeader title="Signing key details" labelId="signing-key-details-title" />
      <ModalBody>
        <DescriptionList isHorizontal style={{ rowGap: "1rem" }}>
          <DescriptionListGroup>
            <DescriptionListTerm>Status</DescriptionListTerm>
            <DescriptionListDescription>
              <StatusIndicator
                color={SIGNING_KEY_STATE_COLOR[signingKey.state]}
                title={signingKey.state}
              >
                {SIGNING_KEY_STATE_LABEL[signingKey.state]}
              </StatusIndicator>
            </DescriptionListDescription>
          </DescriptionListGroup>
          <DescriptionListGroup>
            <DescriptionListTerm>Fingerprint</DescriptionListTerm>
            <DescriptionListDescription>
              <CopyableValue value={signingKey.fingerprint} />
            </DescriptionListDescription>
          </DescriptionListGroup>
          <DescriptionListGroup>
            <DescriptionListTerm>Key ID</DescriptionListTerm>
            <DescriptionListDescription>
              <code>{signingKey.key_id}</code>
            </DescriptionListDescription>
          </DescriptionListGroup>
          <DescriptionListGroup>
            <DescriptionListTerm>Identity</DescriptionListTerm>
            <DescriptionListDescription>
              {signingKey.identity_name}
              {signingKey.identity_email ? ` <${signingKey.identity_email}>` : ""}
            </DescriptionListDescription>
          </DescriptionListGroup>
          <DescriptionListGroup>
            <DescriptionListTerm>Algorithm</DescriptionListTerm>
            <DescriptionListDescription>
              {signingKey.algorithm.toUpperCase()}
            </DescriptionListDescription>
          </DescriptionListGroup>
          <DescriptionListGroup>
            <DescriptionListTerm>Generated by</DescriptionListTerm>
            <DescriptionListDescription>
              {signingKey.generated_by}
            </DescriptionListDescription>
          </DescriptionListGroup>
          <DescriptionListGroup>
            <DescriptionListTerm>Created</DescriptionListTerm>
            <DescriptionListDescription>
              <DateValue value={signingKey.created_at} />
            </DescriptionListDescription>
          </DescriptionListGroup>
          <DescriptionListGroup>
            <DescriptionListTerm>Activated</DescriptionListTerm>
            <DescriptionListDescription>
              <DateValue value={signingKey.activated_at} />
            </DescriptionListDescription>
          </DescriptionListGroup>
          <DescriptionListGroup>
            <DescriptionListTerm>Expires</DescriptionListTerm>
            <DescriptionListDescription>
              {signingKey.expires_at ? (
                <DateValue value={signingKey.expires_at} />
              ) : (
                "Never"
              )}
            </DescriptionListDescription>
          </DescriptionListGroup>
          <DescriptionListGroup>
            <DescriptionListTerm>Retiring since</DescriptionListTerm>
            <DescriptionListDescription>
              <DateValue value={signingKey.retiring_at} />
            </DescriptionListDescription>
          </DescriptionListGroup>
          <DescriptionListGroup>
            <DescriptionListTerm>Retired</DescriptionListTerm>
            <DescriptionListDescription>
              <DateValue value={signingKey.retired_at} />
            </DescriptionListDescription>
          </DescriptionListGroup>
          <DescriptionListGroup>
            <DescriptionListTerm>Public key URL</DescriptionListTerm>
            <DescriptionListDescription>
              {signingKey.state === "active" ? (
                <CopyableValue
                  value={`${window.location.origin}${signingKey.public_key_url}`}
                  isCode={false}
                />
              ) : (
                <Content component="small">
                  Only the active key is served at the public key URL.
                </Content>
              )}
            </DescriptionListDescription>
          </DescriptionListGroup>
        </DescriptionList>

        {signingKey.state === "active" || signingKey.state === "next" ? (
          <KeyPulpServicesStatus keyId={signingKey.id} />
        ) : null}
      </ModalBody>
      <ModalFooter>
        <Flex
          justifyContent={{ default: "justifyContentFlexEnd" }}
          style={{ width: "100%" }}
        >
          <FlexItem>
            <Button variant="link" onClick={onClose}>
              Close
            </Button>
          </FlexItem>
        </Flex>
      </ModalFooter>
    </Modal>
  );
}
