#!/bin/bash
# Generates one Podman Quadlet unit (systemd --user) from
# deployment/podman/*.yaml and drives it via systemctl - not
# `podman play kube` directly (that was this script's old mechanism; see git
# history if you need it). `init` and `up` auto-generate 00-secret.yaml the
# first time it is missing; neither overwrites an existing secrets file.
#
# ONE Quadlet unit, ~/.config/containers/systemd/pulpit-stack.kube
# (regenerated by every `up`), covering the whole stack - Redis, Pulp, and
# Pulpit together, in that Yaml= order (00-secret.yaml/00-configmap.yaml
# applied alongside them, same "same invocation" need `podman play kube`
# always had - see README.md). Neither is rendered/templated by this
# script - edit 00-configmap.yaml directly (notably `PULPIT_PUBLIC_ORIGIN`
# and the CSRF/content/Ansible/PyPI origin fields) before running `up`; see
# that file's own comments.
#
# Deliberately a single unit, not one per component: `simonverbois/pulpit`
# and `simonverbois/pulp-pulpit` are built and published together, from the
# same commit, in the same CI run, on every release (`.forgejo/workflows/
# release.yml`, and docs/adr/0008-colocated-signing-reconciler.md - pulp-
# pulpit's rebuild cadence is deliberately tied to this project's own
# releases, not upstream Pulp's) - splitting them into separately
# auto-updated units would let one advance to a newer release while the
# other stayed on an older cached digest, exactly the kind of drift
# `AutoUpdate=registry` should not introduce. One unit means `podman
# auto-update` (see `update` below) always keeps every image in the stack
# at the same release together - including Redis's own upstream tag, an
# accepted side effect of the same simplicity. `ExecStartPost=` sets Pulp's
# admin password (no postStart-hook equivalent, same limitation the old
# mechanism worked around - set-admin-password.sh); pulpit.yaml's own
# `initContainers: wait-for-pulp` (not this script) is what makes it safe
# for `podman kube play` to create every pod from one invocation without
# this script staging them - it already blocks the pulpit container from
# starting until pulp responds.
#
# Usage:
#   ./deployment/podman/deploy.sh init    # generate secrets without deploying
#   ./deployment/podman/deploy.sh up      # (re)generate the unit, (re)deploy
#   ./deployment/podman/deploy.sh update  # pull + restart with any newer image (podman auto-update)
#   ./deployment/podman/deploy.sh down    # stop (PVCs/volumes/unit kept)
#   ./deployment/podman/deploy.sh reset   # delete the unit, runtime resources, and data
#
# Images are pinned to :latest in redis.yaml/pulp.yaml/pulpit.yaml - edit
# those files directly to deploy a specific tag (`up` always restarts the
# unit, so a manifest/tag edit is picked up the same way as any other
# config change).
#
# Requires a Podman new enough to ship the Quadlet generator
# (`/usr/libexec/podman/quadlet`, Podman >= 4.4) and, for the unit to
# survive past this shell session/across reboots without an active login,
# `loginctl enable-linger "$(whoami)"` (this script does not run that for
# you - it changes host-wide login behavior, not something to do silently).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
cd "${REPO_ROOT}"

QUADLET_DIR="${XDG_CONFIG_HOME:-${HOME}/.config}/containers/systemd"

usage() {
    cat <<EOF
Usage: $0 <init|up|update|down|reset>

Commands:
  init    Generate the local secrets file without deploying anything.
  up      (Re)generate the Quadlet unit and (re)deploy, preserving existing data.
  update  Pull and apply any newer image in the stack (podman auto-update).
  down    Stop Pulpit, preserving volumes, the Quadlet unit, and the local secrets file.
  reset   Stop Pulpit, remove the Quadlet unit, and permanently delete its volumes and images.

Environment:
  PULPIT_RESET_CONFIRM  Set to yes to run reset non-interactively.
EOF
}

wait_healthy() {
    local container="$1"
    local attempt=0
    echo "Waiting for ${container} to become healthy..."
    until [ "$(podman inspect "${container}" --format '{{.State.Health.Status}}' 2>/dev/null)" = "healthy" ]; do
        attempt=$((attempt + 1))
        if [ "${attempt}" -ge 60 ]; then
            echo "${container} did not become healthy in time - check: podman logs ${container}" >&2
            exit 1
        fi
        sleep 5
    done
    echo "${container} is healthy."
}

# Generates 00-secret.yaml from the .example file with real random values.
# Only called when 00-secret.yaml doesn't exist yet - never overwrites one.
generate_secret_file() {
    echo "No deployment/podman/00-secret.yaml found - generating one with fresh secrets..." >&2

    local pulp_secret_key pulpit_core_secret_key pulp_admin_password
    pulp_secret_key="$(openssl rand -hex 32)"
    pulpit_core_secret_key="$(openssl rand -base64 32 | tr '+/' '-_')"
    pulp_admin_password="$(openssl rand -base64 18 | tr -d '=+/')"

    sed -E \
        -e "s#^(  PULP_SECRET_KEY:).*#\1 \"${pulp_secret_key}\"#" \
        -e "s#^(  PULP_ADMIN_PASSWORD:).*#\1 \"${pulp_admin_password}\"#" \
        -e "s#^(  PULPIT_CORE_SECRET_KEY:).*#\1 \"${pulpit_core_secret_key}\"#" \
        "${SCRIPT_DIR}/00-secret.example.yaml" > "${SCRIPT_DIR}/00-secret.yaml"
    chmod 600 "${SCRIPT_DIR}/00-secret.yaml"

    echo "Generated ${SCRIPT_DIR}/00-secret.yaml." >&2
    echo >&2
    echo "Pulp admin password: ${pulp_admin_password}" >&2
    echo "(shown once here - store it somewhere safe; it's also readable from 00-secret.yaml)" >&2
    echo >&2
}

# Writes the single Quadlet unit file, always overwriting - `up` is meant to
# be safely re-runnable (task: "deploy or update, preserving existing
# data"), same as a plain YAML edit followed by re-running `podman play
# kube` used to be. Absolute paths throughout (SCRIPT_DIR is already
# absolute), so no `SetWorkingDirectory=` is needed for `Yaml=` resolution.
write_quadlet_unit() {
    mkdir -p "${QUADLET_DIR}"
    chmod +x "${SCRIPT_DIR}/set-admin-password.sh"

    cat > "${QUADLET_DIR}/pulpit-stack.kube" <<EOF
# Generated by deployment/podman/deploy.sh - do not edit by hand, it is
# overwritten on every 'deploy.sh up'. Edit redis.yaml/pulp.yaml/pulpit.yaml
# (or this script) instead.
[Unit]
Description=Pulpit stack (Redis + Pulp + Pulpit)
Wants=network-online.target
After=network-online.target

[Kube]
Yaml=${SCRIPT_DIR}/00-secret.yaml
Yaml=${SCRIPT_DIR}/00-configmap.yaml
Yaml=${SCRIPT_DIR}/redis.yaml
Yaml=${SCRIPT_DIR}/pulp.yaml
Yaml=${SCRIPT_DIR}/pulpit.yaml
# Keeps every image in the stack on the same release together - see this
# file's own header comment on why this is one unit, not one per component.
AutoUpdate=registry
ExitCodePropagation=any

[Service]
Restart=on-failure
RestartSec=10
# No postStart-hook equivalent under \`podman kube play\` - see
# set-admin-password.sh and pulp.yaml's own comment. Blocks this unit from
# being reported started until Pulp's admin password is actually set.
ExecStartPost=${SCRIPT_DIR}/set-admin-password.sh

[Install]
WantedBy=default.target
EOF
}

init() {
    if [ ! -f "${SCRIPT_DIR}/00-secret.yaml" ]; then
        generate_secret_file
    else
        echo "Keeping existing ${SCRIPT_DIR}/00-secret.yaml."
    fi

    echo "Initialization complete. Edit 00-configmap.yaml (PULPIT_PUBLIC_ORIGIN and friends) if"
    echo "you haven't already, then run '$0 up' to deploy."
}

up() {
    if [ ! -f "${SCRIPT_DIR}/00-secret.yaml" ]; then
        generate_secret_file
    fi

    write_quadlet_unit
    systemctl --user daemon-reload

    # `restart` (not `start`) so a manifest/tag/config edit is always picked
    # up on a re-run, exactly like the old script's unconditional
    # `podman play kube` re-apply - `systemctl ... --now` alone would be a
    # no-op against an already-running unit. pulpit.yaml's own
    # `initContainers: wait-for-pulp` is what makes starting everything as
    # one unit safe - it blocks the pulpit container until pulp responds,
    # so this script doesn't need to stage redis/pulp/pulpit itself anymore.
    systemctl --user enable pulpit-stack.service
    systemctl --user restart pulpit-stack.service
    wait_healthy pulp-pulp
    wait_healthy pulpit-pulpit

    echo
    echo "Pulpit is up (see PULPIT_PUBLIC_ORIGIN in 00-configmap.yaml for the URL)."
    echo
    echo "This is a systemd --user unit: to keep running after you log out (e.g. a fresh"
    echo "boot with no active session), enable lingering once: loginctl enable-linger \"\$(whoami)\""
}

update() {
    echo "Checking for and pulling any newer image in the stack (podman auto-update, registry policy)..."
    echo "(Redis, Pulp, and Pulpit are all covered - see deploy.sh's own header comment on why.)"
    podman auto-update
    echo
    echo "Any update found above already triggered a restart of pulpit-stack.service. Check status with:"
    echo "  systemctl --user status pulpit-stack.service"
}

down() {
    systemctl --user stop pulpit-stack.service 2>/dev/null || true
}

confirm_reset() {
    echo "WARNING: reset permanently deletes every Pulp/Pulpit Podman volume and removes its images when unused." >&2
    if [ "${PULPIT_RESET_CONFIRM:-}" = "yes" ]; then
        return
    fi
    if [ ! -t 0 ]; then
        echo "Refusing non-interactive reset. Set PULPIT_RESET_CONFIRM=yes to confirm." >&2
        exit 1
    fi
    read -r -p "Type 'reset' to continue: " confirmation
    if [ "${confirmation}" != "reset" ]; then
        echo "Reset cancelled."
        exit 0
    fi
}

reset() {
    confirm_reset

    systemctl --user stop pulpit-stack.service 2>/dev/null || true
    systemctl --user disable pulpit-stack.service 2>/dev/null || true
    rm -f "${QUADLET_DIR}/pulpit-stack.kube"
    systemctl --user daemon-reload

    # Exact manifest-owned volume names only; this also covers partial stacks
    # where a pod is already absent and stopping the units above cannot
    # discover every remaining PVC-backed volume.
    local volume
    for volume in \
        pulpit-data \
        pulpit-tls \
        pulpit-signing-gnupghome \
        pulpit-signing-scripts \
        pulp-var-lib-containers \
        pulp-var-lib-pgsql \
        pulp-var-lib-pulp \
        pulp-etc \
        pulp-init-admin-password-script; do
        if podman volume exists "${volume}"; then
            podman volume rm --force "${volume}"
        fi
    done

    local image
    while IFS= read -r image; do
        if podman image exists "${image}"; then
            if ! podman image rm "${image}"; then
                echo "Keeping image ${image}: another container still uses it." >&2
            fi
        fi
    done < <(
        awk '$1 == "image:" { gsub(/"/, "", $2); print $2 }' \
            "${SCRIPT_DIR}/redis.yaml" \
            "${SCRIPT_DIR}/pulp.yaml" \
            "${SCRIPT_DIR}/pulpit.yaml" | sort -u
    )

    echo "Reset complete. The Quadlet unit, Podman pods/containers, and data volumes were permanently deleted; YAML files and secrets were preserved."
}

if [ "$#" -eq 0 ]; then
    usage
    exit 0
fi

action="$1"
shift

if [ "$#" -ne 0 ]; then
    usage >&2
    exit 1
fi

case "${action}" in
    init) init ;;
    up) up ;;
    update) update ;;
    down) down ;;
    reset) reset ;;
    help|-h|--help) usage ;;
    *)
        usage >&2
        exit 1
        ;;
esac
