#!/bin/sh
# ExecStartPost helper for the pulpit-stack Quadlet unit
# (~/.config/containers/systemd/pulpit-stack.kube, generated by deploy.sh).
#
# `podman play kube` has no postStart-hook equivalent (see pulp.yaml's own
# comment) - under the old bash-driven `deploy.sh up`, this same step ran
# as a plain `podman exec` once the script's own wait_healthy loop said
# `pulp-pulp` was healthy. Under systemd/Quadlet, ExecStartPost is the
# closest equivalent: it runs once `podman kube play` has created the pod's
# containers, but before the unit is considered fully started - blocking
# `systemctl start pulpit-stack.service` (and therefore deploy.sh's own
# `up`) until this finishes.
#
# The container itself may take a little longer to actually accept exec
# calls than `podman kube play` takes to return, so this only waits for
# that - the actual in-container script
# (pulp-init-admin-password-script ConfigMap, pulp.yaml) already retries
# internally (up to 150s) until Pulp itself has finished initializing.
set -eu

attempt=0
max_attempts=60
until podman exec pulp-pulp true 2>/dev/null; do
    attempt=$((attempt + 1))
    if [ "${attempt}" -ge "${max_attempts}" ]; then
        echo "set-admin-password: pulp-pulp container did not appear within $((max_attempts * 2))s" >&2
        exit 1
    fi
    sleep 2
done

exec podman exec pulp-pulp sh /usr/local/bin/pulpit-init-admin-password.sh
