from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.core.auth import FullUser, require_staff_user
from app.core.database import get_db
from app.core.jobs.schemas import JobRead
from app.core.jobs.service import enqueue_job

router = APIRouter(prefix="/selfsigned", dependencies=[Depends(require_staff_user)])


@router.post("/regenerate", response_model=JobRead, status_code=202)
def regenerate_selfsigned(
    db: Session = Depends(get_db),
    user: FullUser = Depends(require_staff_user),
) -> JobRead:
    """Replaces whatever certificate is currently active with a fresh
    self-signed one - e.g. an administrator moving away from a manual/FreeIPA
    certificate back to the zero-config fallback."""
    job = enqueue_job(
        db,
        "tls.generate_selfsigned",
        {"triggered_by": "manual", "notes": f"Regenerated by {user.username}."},
        requested_by=user.username,
    )
    db.commit()
    return JobRead.model_validate(job)
