"""Loads the checked-in manifest of Pulp API paths this app's frontend
depends on (scripts/api/extract-used-endpoints.mjs, regenerated by hand via
`npm run api:extract-endpoints` - same "checked in, manually regenerated"
convention as src/api/generated/*/schema.d.ts, ADR 0004). Bundled into this
image the same way as every other file under app/ (Dockerfile COPYs the
whole pulpit-core/app directory), so no separate build step or volume is
needed here.
"""

import json
from functools import lru_cache
from pathlib import Path

_MANIFEST_PATH = Path(__file__).parent / "used_endpoints.json"


@lru_cache
def used_endpoints() -> list[str]:
    return json.loads(_MANIFEST_PATH.read_text())
