"""single active key, drop resign toggle

Revision ID: 6275d356cd99
Revises: 72f928f61c80
Create Date: 2026-09-02 13:25:02.285879
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '6275d356cd99'
down_revision: str | None = '72f928f61c80'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Nullable first, then backfilled, then tightened to NOT NULL - any
    # existing row's fingerprint is recoverable losslessly from its own
    # `bootstrap_command` text (a bare 40-hex-char token in a fixed
    # position - see pulp_bootstrap.py's pre-this-migration command
    # format), so this is a real backfill, not a placeholder default.
    op.add_column("signing_pulp_services", sa.Column("fingerprint", sa.String(length=64), nullable=True))
    op.execute(
        "UPDATE signing_pulp_services "
        r"SET fingerprint = substring(bootstrap_command from '[0-9A-Fa-f]{40}') "
        "WHERE fingerprint IS NULL"
    )
    op.alter_column("signing_pulp_services", "fingerprint", nullable=False)
    op.drop_column("signing_settings", "resign_existing_packages_enabled")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signing_settings', sa.Column('resign_existing_packages_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('signing_pulp_services', 'fingerprint')
    # ### end Alembic commands ###
