"""initial schema

Revision ID: 72f928f61c80
Revises: 
Create Date: 2026-09-01 19:44:47.619719
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '72f928f61c80'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events_log',
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_module', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_log_event_type'), 'events_log', ['event_type'], unique=False)
    op.create_table('jobs',
    sa.Column('job_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('requested_by', sa.String(length=150), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status_scheduled_at', 'jobs', ['status', 'scheduled_at'], unique=False)
    op.create_table('signing_keys',
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('key_id', sa.String(length=40), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('identity_name', sa.String(length=255), nullable=False),
    sa.Column('identity_email', sa.String(length=255), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('public_key_armor', sa.Text(), nullable=False),
    sa.Column('generated_by', sa.String(length=64), nullable=False),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('retiring_at', sa.DateTime(), nullable=True),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signing_keys_fingerprint'), 'signing_keys', ['fingerprint'], unique=True)
    op.create_index(op.f('ix_signing_keys_state'), 'signing_keys', ['state'], unique=False)
    op.create_table('signing_settings',
    sa.Column('signing_enabled', sa.Boolean(), nullable=False),
    sa.Column('package_signing_enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata_signing_enabled', sa.Boolean(), nullable=False),
    sa.Column('key_name', sa.String(length=255), nullable=False),
    sa.Column('identity_name', sa.String(length=255), nullable=False),
    sa.Column('identity_email', sa.String(length=255), nullable=False),
    sa.Column('algorithm', sa.String(length=64), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('public_key_filename', sa.String(length=255), nullable=False),
    sa.Column('rpm_signing_service_name', sa.String(length=255), nullable=False),
    sa.Column('metadata_signing_service_name', sa.String(length=255), nullable=False),
    sa.Column('auto_rotation_enabled', sa.Boolean(), nullable=False),
    sa.Column('rotation_generate_before_days', sa.Integer(), nullable=False),
    sa.Column('rotation_activate_before_days', sa.Integer(), nullable=False),
    sa.Column('key_retention_days', sa.Integer(), nullable=False),
    sa.Column('resign_existing_packages_enabled', sa.Boolean(), nullable=False),
    sa.Column('allow_indefinite_validity', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signing_pulp_services',
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('signing_key_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('pulp_href', sa.String(length=512), nullable=True),
    sa.Column('bootstrap_command', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signing_key_id'], ['signing_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signing_rotations',
    sa.Column('triggered_by', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('from_key_id', sa.UUID(), nullable=True),
    sa.Column('to_key_id', sa.UUID(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_key_id'], ['signing_keys.id'], ),
    sa.ForeignKeyConstraint(['to_key_id'], ['signing_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signing_rotations')
    op.drop_table('signing_pulp_services')
    op.drop_table('signing_settings')
    op.drop_index(op.f('ix_signing_keys_state'), table_name='signing_keys')
    op.drop_index(op.f('ix_signing_keys_fingerprint'), table_name='signing_keys')
    op.drop_table('signing_keys')
    op.drop_index('ix_jobs_status_scheduled_at', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_events_log_event_type'), table_name='events_log')
    op.drop_table('events_log')
    # ### end Alembic commands ###
